export const getMockStock = () => {
  const stock = {
    Ticker: 'BAH',
    Beta: '0.73',
    Company: 'Booz Allen Hamilton Holding Corporation',
    Country: 'USA',
    'Curr R': '2.00',
    'Debt/Eq': '2.21',
    Dividend: '1.75%',
    'Fwd P/E': '20.75',
    Industry: 'Consulting Services',
    'LTDebt/Eq': '2.14',
    'Market Cap': '11.63B',
    'No.': '132',
    'Oper M': '9.90%',
    Outstanding: '137.88M',
    'P/E': '21.59',
    'P/FCF': '16.81',
    'Payout Ratio': '31.90%',
    'Perf Month': '5.77%',
    'Perf Week': '2.93%',
    'Perf YTD': '-2.88%',
    Price: '84.67',
    'Profit M': '6.80%',
    'Quick R': '2.00',
    ROA: '10.60%',
    ROE: '56.70%',
    ROI: '18.80%',
    Recom: '2',
    'Recom Yahoo': '3',
    'Recom Zacks': '3',
    Sector: 'Industrials',
  };
  const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
  let ticker = '';
  let length = (Math.floor(Math.random() * 10) % 5) + 1;
  while (length) {
    length -= 1;
    ticker +=
      letters[(Math.floor(Math.random() * 10) % (letters.length - 1)) + 1];
  }
  stock.Ticker = ticker;
  return stock;
};

export const stockMocks = [
  {
    Ticker: 'BAH',
    Beta: '0.73',
    Company: 'Booz Allen Hamilton Holding Corporation',
    Country: 'USA',
    'Curr R': '2.00',
    'Debt/Eq': '2.21',
    Dividend: '1.75%',
    'Fwd P/E': '20.75',
    Industry: 'Consulting Services',
    'LTDebt/Eq': '2.14',
    'Market Cap': '11.63B',
    'No.': '132',
    'Oper M': '9.90%',
    Outstanding: '137.88M',
    'P/E': '21.59',
    'P/FCF': '16.81',
    'Payout Ratio': '31.90%',
    'Perf Month': '5.77%',
    'Perf Week': '2.93%',
    'Perf YTD': '-2.88%',
    Price: '84.67',
    'Profit M': '6.80%',
    'Quick R': '2.00',
    ROA: '10.60%',
    ROE: '56.70%',
    ROI: '18.80%',
    Recom: '2',
    'Recom Yahoo': '3',
    'Recom Zacks': '3',
    Sector: 'Industrials',
  },
  {
    Ticker: 'FB',
    Beta: '0.73',
    Company: 'Booz Allen Hamilton Holding Corporation',
    Country: 'USA',
    'Curr R': '2.00',
    'Debt/Eq': '2.21',
    Dividend: '1.75%',
    'Fwd P/E': '20.75',
    Industry: 'Consulting Services',
    'LTDebt/Eq': '2.14',
    'Market Cap': '11.63B',
    'No.': '132',
    'Oper M': '9.90%',
    Outstanding: '137.88M',
    'P/E': '21.59',
    'P/FCF': '16.81',
    'Payout Ratio': '31.90%',
    'Perf Month': '5.77%',
    'Perf Week': '2.93%',
    'Perf YTD': '-2.88%',
    Price: '84.67',
    'Profit M': '6.80%',
    'Quick R': '2.00',
    ROA: '10.60%',
    ROE: '56.70%',
    ROI: '18.80%',
    Recom: '2',
    'Recom Yahoo': '3',
    'Recom Zacks': '3',
    Sector: 'Industrials',
  },
];
